stages:
  - build
  - test

variables:
  # Set Playwright environment variable to skip installing Firefox and WebKit
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "true"

workflow:
  rules:
   # Rule for nightly job
   - if: '$CI_PIPELINE_SOURCE == "schedule" && $NIGHTLY_CORE_RUN == "true" && $CI_COMMIT_BRANCH == "main"'
     when: always
   - if: '$CI_PIPELINE_SOURCE == "schedule" && $NIGHTLY_BACKOFFICE_RUN == "true" && $CI_COMMIT_BRANCH == "main"'
     when: always
   # Rule for jobs run on MR
   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $APP_NAME == null'
     when: always  # Pipeline runs on merge requests
   # Push pipeline workflow (excluding main branch)
   - if: '$CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE == "push"'
     when: always  # Pipeline runs on non-main branch pushes
   # Rule for downstream pipeline for merges to services repos
   - if: '$APP_NAME != null'
     when: always
   # Rule for launching core tests from gitlab ui
   - if: '$CI_PIPELINE_SOURCE == "web" && $TESTS_GROUP == "core"'
     when: always
    # Rule for launching backoffice tests from gitlab ui
   - if: '$CI_PIPELINE_SOURCE == "web" && $TESTS_GROUP == "backoffice"'
     when: always
   # Default: Disable pipeline for other scenarios
   - when: never

job_build:
  timeout: 1 hour
  stage: build
  image: gradle:8.10.0-jdk22
  rules:
    - if: '$APP_NAME == null'
  script:
    - echo "Building the project"
    - ./gradlew clean
    - ./gradlew build -x test -x spotlessCheck
    - echo "BUILD SUCCESS"

#Jobe for checking code format with spotless
job_code_check:
  timeout: 30 minutes
  stage: build
  needs: ["job_build"]
  image: gradle:8.10.0-jdk22
  rules:
    - if: '$APP_NAME == null'
  script:
    - echo "Checking the code"
    - ./gradlew spotlessCheck
    - echo "CODE CHECK SUCCESS"

#Job to check that base tests are working
job_run_minimal_tests:
  timeout: 3 hours
  stage: test
  needs: ["job_build"]
  image: gradle:8.10.0-jdk22
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $APP_NAME == null'
    - if: '$CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE == "push" && $APP_NAME == null'
  script:
    - echo "Run the minimal tests set to ensure that framework works"
    - ./gradlew installDeps
    - ./gradlew installChromium
    - ./gradlew testBuildCheck
    - echo "Run minimal tests set SUCCESS"

#Job for core team nightly tests
job_test_core:
  timeout: 3 hours
  stage: test
  needs: ["job_build"]
  image: gradle:8.10.0-jdk22
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $NIGHTLY_CORE_RUN == "true" && $CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "web" && $TESTS_GROUP == "core"'
  variables:
    ALLURE_LAUNCH_NAME: "[Core team] Nightly run at $CI_PIPELINE_CREATED_AT"
    ALLURE_ENDPOINT: http://allure.vindex-test.risk-vantagefx.com/
    ALLURE_PROJECT_ID: 3
    ALLURE_RESULTS: allure-results
    RUNNER: "GITLAB_CI"
    TAG: 'team_core'
  before_script:
    - wget --output-document=allurectl --quiet https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64
    - chmod +x allurectl
  script:
    - echo "Running tests"
    - ./gradlew installDeps
    - ./gradlew installChromium
    - ./allurectl watch -- gradle clean testSmokeCore
    - echo "TEST SUCCESS"
  artifacts:
    when: always
    paths:
      - playwright-report
      - build/reports/
      - allure-results
      - test-output/videos
    expire_in: 1 day

#Job for backoffice team nightly tests
job_test_backoffice:
  timeout: 3 hours
  stage: test
  needs: ["job_build"]
  image: gradle:8.10.0-jdk22
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $NIGHTLY_BACKOFFICE_RUN == "true" && $CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "web" && $TESTS_GROUP == "backoffice"'
  variables:
    ALLURE_LAUNCH_NAME: "[Backoffice team] Nightly run at $CI_PIPELINE_CREATED_AT"
    ALLURE_ENDPOINT: http://allure.vindex-test.risk-vantagefx.com/
    ALLURE_PROJECT_ID: 4
    ALLURE_RESULTS: allure-results
    RUNNER: "GITLAB_CI"
  before_script:
    - wget --output-document=allurectl --quiet https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64
    - chmod +x allurectl
  script:
    - echo "Running tests"
    - ./gradlew installDeps
    - ./gradlew installChromium
    - ./allurectl watch -- gradle clean testSmokeBackoffice
    - echo "TEST SUCCESS"
  artifacts:
    when: always
    paths:
      - playwright-report
      - build/reports/
      - allure-results
      - test-output/videos
    expire_in: 1 day

#Job to launch tests by connected service
job_test_downstream_end_to_end:
  timeout: 3 hours
  stage: test
  image: gradle:8.10.0-jdk22
  rules:
    - if: '$APP_NAME != null'
      when: always
  variables:
    ALLURE_LAUNCH_NAME: "[Core team] Triggered by $APP_NAME"
    ALLURE_ENDPOINT: http://allure.vindex-test.risk-vantagefx.com/
    ALLURE_PROJECT_ID: 3
    ALLURE_RESULTS: allure-results
    RUNNER: "GITLAB_CI"
  before_script:
    - wget --output-document=allurectl --quiet https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64
    - chmod +x allurectl
  script:
    - echo "Running tests"
    - |
      if [ "$APP_NAME" == "clickhouse-api" ]; then
        ./allurectl watch -- gradle clean testClickhouseApiService
      elif [ "$APP_NAME" == "event-generator" ]; then
        ./allurectl watch -- gradle clean testEventGeneratorService
      elif [ "$APP_NAME" == "connection-search-service" ]; then
        ./allurectl watch -- gradle clean testConnectionSearchApiService
      fi
    - echo "TEST SUCCESS"
  artifacts:
    when: always
    paths:
      - build/reports/
      - allure-results
    expire_in: 1 day