plugins {
    id 'java'
    id 'com.diffplug.spotless' version '6.25.0'
    id 'org.openapi.generator' version '7.8.0'
}

group = 'antifraud'
version = '1.0'

repositories {
    mavenCentral()
}

def ownerVersion = '1.0.12'
def playwrightVersion = '1.45.0'
def okhttpVersion = '4.12.0'
def hamcrestVersion = '3.0'
def slf4jVersion = '2.0.12'
def junitBomVersion = '5.10.2'
def junitJupiterApiVersion = '5.10.3'
def allureBomVersion = '2.25.0'
def jacksonVersion = '2.17.2'
def postgreVersion = '42.1.4'
def mysqlVersion = '8.0.32'
def clickhouseVersion = '0.6.0'
def kafkaClientVersion = '3.6.0'
def imageComparisonVersion = '4.4.0'
def jsonVersion = '20240303'
def httpcomponentsVersion = '5.2.3'
def commonsConfigurationVersion = '1.7'

dependencies {
    // Junit
    implementation platform("org.junit:junit-bom:$junitBomVersion")
    implementation "org.junit.jupiter:junit-jupiter-api:$junitJupiterApiVersion"
    implementation group: 'commons-configuration', name: 'commons-configuration', version: "$commonsConfigurationVersion"
    implementation group: 'org.json', name: 'json', version: "$jsonVersion"

    //Playwright
    implementation "com.microsoft.playwright:playwright:$playwrightVersion"

    //Config
    implementation "org.aeonbits.owner:owner:$ownerVersion"

    //Rest api
    implementation "com.squareup.okhttp3:okhttp:$okhttpVersion"

    //Json parsing
    implementation "com.fasterxml.jackson.core:jackson-databind:$jacksonVersion"
    implementation "com.fasterxml.jackson.core:jackson-core:$jacksonVersion"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:$jacksonVersion"

    //Hamcrest matchers
    implementation "org.hamcrest:hamcrest:$hamcrestVersion"

    //Database
    implementation "org.postgresql:postgresql:$postgreVersion"
    implementation "mysql:mysql-connector-java:$mysqlVersion"
    implementation "com.clickhouse:clickhouse-jdbc:$clickhouseVersion"
    implementation "org.apache.httpcomponents.client5:httpclient5:$httpcomponentsVersion"

    //Allure
    implementation platform("io.qameta.allure:allure-bom:$allureBomVersion")
    implementation "io.qameta.allure:allure-junit5"
    implementation "org.junit.jupiter:junit-jupiter-api"
    runtimeOnly "org.junit.jupiter:junit-jupiter-engine"
    implementation "org.junit.jupiter:junit-jupiter"

    // slf4j
    implementation "org.slf4j:slf4j-simple:$slf4jVersion"

    //Kafka
    implementation "org.apache.kafka:kafka-clients:$kafkaClientVersion"

    //Visual testing
    implementation "com.github.romankh3:image-comparison:$imageComparisonVersion"

}

spotless {
    java {
        removeUnusedImports()
        cleanthat()
                .addMutator('ErrorProneMutators')
                .addMutator('PMDMutators')
                .addMutator('SafeAndConsensual')
                .addMutator('SonarMutators')
                .addMutator('LocalVariableTypeInference')
                .addMutator('RemoveExplicitCallToSuper')
                .addMutator('UnnecessarySemicolon')
                .addMutator('UseTextBlocks')
        formatAnnotations()
        palantirJavaFormat()
    }
}

test {
    useJUnitPlatform()
}

task installChromium(type: JavaExec) {
    mainClass = 'com.microsoft.playwright.CLI'
    args = ['install', 'chromium']
    classpath = sourceSets.main.runtimeClasspath
}

task installDeps(type: JavaExec) {
    mainClass = 'com.microsoft.playwright.CLI'
    args = ['install-deps']
    classpath = sourceSets.main.runtimeClasspath
}

task testBuildCheck(type: Test) {
    useJUnitPlatform(){
        includeTags "build_check"
    }
}

task testSuiteSmoke(type: Test) {
    useJUnitPlatform() {
        includeTags 'suite_smoke'
    }
}

task testSmokeBackoffice(type: Test) {
    useJUnitPlatform() {
        includeTags 'team_backoffice'
    }
}

task testSmokeCore(type: Test) {
    useJUnitPlatform(){
        includeTags "team_core"
    }
}

sourceSets {
    main {
        java {
            srcDir "${buildDir}/generated/src/main/java"
        }
    }
}

task codegenEventGenerator(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    def packageName = "com.hytechc.antifraud.EventGenerator.events"
    generatorName.set("java")
    library.set("native")
    inputSpec.set("$projectDir/src/main/resources/eventGeneratorOpenApi.yaml")
    outputDir.set("$buildDir/generated")
    invokerPackage.set(packageName)
    apiPackage.set(packageName)
    modelPackage.set(packageName)
    generateApiTests.set(false)
    generateModelTests.set(false)
    generateApiDocumentation.set(false)
    configOptions.putAll([
            "dateLibrary": "java8",
            "useJakartaEe": "true",
            "openApiNullable": "false",
    ])
}

task codegenClickhouseApi(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    def packageName = "com.hytechc.antifraud.EventGenerator.events"
    generatorName.set("java")
    library.set("native")
    inputSpec.set("$projectDir/src/main/resources/clickhouseApiOpenApi.yaml.yaml")
    outputDir.set("$buildDir/generated")
    invokerPackage.set(packageName)
    apiPackage.set(packageName)
    modelPackage.set(packageName)
    generateApiTests.set(false)
    generateModelTests.set(false)
    generateApiDocumentation.set(false)
    configOptions.putAll([
            "dateLibrary": "java8",
            "useJakartaEe": "true",
            "openApiNullable": "false",
    ])
}