plugins {
    id 'java'
    id 'com.diffplug.spotless' version '6.25.0'
    id 'org.gradle.test-retry' version '1.6.0'
}

def properties = new Properties()
file("src/main/resources/config/config.properties").withInputStream { stream ->
    properties.load(stream)
}

group = 'antifraud'
version = '1.0'

repositories {
    mavenCentral()
}

def ownerVersion = '1.0.12'
def playwrightVersion = '1.45.0'
def okhttpVersion = '4.12.0'
def hamcrestVersion = '3.0'
def slf4jVersion = '2.0.12'
def junitBomVersion = '5.10.2'
def junitJupiterApiVersion = '5.10.3'
def allureBomVersion = '2.25.0'
def jacksonVersion = '2.17.2'
def postgresVersion = '42.7.3'
def mysqlVersion = '8.0.32'
def clickhouseVersion = '0.6.0'
def kafkaClientVersion = '3.6.0'
def imageComparisonVersion = '4.4.0'
def jsonVersion = '20240303'
def httpcomponentsVersion = '5.2.3'
def commonsConfigurationVersion = '1.7'
def fakerVersion = '2.4.1'

dependencies {
    // Junit
    implementation platform("org.junit:junit-bom:$junitBomVersion")
    implementation "org.junit.jupiter:junit-jupiter-api:$junitJupiterApiVersion"
    implementation group: 'commons-configuration', name: 'commons-configuration', version: "$commonsConfigurationVersion"
    implementation group: 'org.json', name: 'json', version: "$jsonVersion"

    //Playwright
    implementation "com.microsoft.playwright:playwright:$playwrightVersion"

    //Config
    implementation "org.aeonbits.owner:owner:$ownerVersion"

    //Rest api
    implementation "com.squareup.okhttp3:okhttp:$okhttpVersion"

    //Json parsing
    implementation "com.fasterxml.jackson.core:jackson-databind:$jacksonVersion"
    implementation "com.fasterxml.jackson.core:jackson-core:$jacksonVersion"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:$jacksonVersion"

    //Hamcrest matchers
    implementation "org.hamcrest:hamcrest:$hamcrestVersion"

    //Database
    implementation "org.postgresql:postgresql:$postgresVersion"
    implementation "mysql:mysql-connector-java:$mysqlVersion"
    implementation "com.clickhouse:clickhouse-jdbc:$clickhouseVersion"
    implementation "org.apache.httpcomponents.client5:httpclient5:$httpcomponentsVersion"

    //Allure
    implementation platform("io.qameta.allure:allure-bom:$allureBomVersion")
    implementation "io.qameta.allure:allure-junit5"
    implementation "org.junit.jupiter:junit-jupiter-api"
    runtimeOnly "org.junit.jupiter:junit-jupiter-engine"
    implementation "org.junit.jupiter:junit-jupiter"

    // slf4j
    implementation "org.slf4j:slf4j-simple:$slf4jVersion"

    //Kafka
    implementation "org.apache.kafka:kafka-clients:$kafkaClientVersion"

    //Visual testing
    implementation "com.github.romankh3:image-comparison:$imageComparisonVersion"

    implementation "net.datafaker:datafaker:$fakerVersion"

}

spotless {
    java {
        removeUnusedImports()
        cleanthat()
                .addMutator('ErrorProneMutators')
                .addMutator('PMDMutators')
                .addMutator('SafeAndConsensual')
                .addMutator('SonarMutators')
                .addMutator('LocalVariableTypeInference')
                .addMutator('RemoveExplicitCallToSuper')
                .addMutator('UnnecessarySemicolon')
                .addMutator('UseTextBlocks')
        formatAnnotations()
    }
}

task createConsumerGroupsFile {
    def group1 = properties.getProperty("testClusterKafkaConsumerGroup1")
    def group2 = properties.getProperty("testClusterKafkaConsumerGroup2")
    doFirst {
        def filePath = "src/main/resources/config/consumer-groups"
        def file = new File(filePath)

        // Write content to the file
        file.text = "$group1\n$group2"

        println "File created at: ${filePath}"
    }
}

tasks.withType(Test) {
    dependsOn(createConsumerGroupsFile)
    // Enable parallel test execution
    maxParallelForks = 2// Set to the number of available processors

    // Optional: Configure parallel execution for classes and methods
    forkEvery = 0 // 0 means it forks once per class. Increase for larger suites.
    systemProperty 'junit.jupiter.execution.parallel.enabled', 'true' // Enable JUnit 5 parallelism

    // Other options
    testLogging {
        events "passed", "failed", "skipped"
    }
}

task installChromium(type: JavaExec) {
    mainClass = 'com.microsoft.playwright.CLI'
    args = ['install', 'chromium']
    classpath = sourceSets.main.runtimeClasspath
}

task installDeps(type: JavaExec) {
    mainClass = 'com.microsoft.playwright.CLI'
    args = ['install-deps']
    classpath = sourceSets.main.runtimeClasspath
}

tasks.withType(Test).configureEach {
    if (System.getenv("IS_GITLAB_CI") == "true") {
        retry {
            maxRetries = 2
            failOnPassedAfterRetry = false // If true, fails the build if a test passes after retrying
        }
    }
    useJUnitPlatform {
        excludeTags 'manual' // Exclude tests tagged with "manual"
    }
}

test {
    useJUnitPlatform()
}

task testBuildCheck(type: Test) {
    useJUnitPlatform(){
        includeTags "build_check"
    }
}

task testSuiteSmoke(type: Test) {
    useJUnitPlatform() {
        includeTags 'suite_smoke'
    }
}

task testSmokeBackoffice(type: Test) {
    useJUnitPlatform() {
        includeTags 'team_backoffice'
    }
}

task testSmokeCore(type: Test) {
    useJUnitPlatform(){
        includeTags "team_core"
    }
}

task testClickhouseApiService(type: Test) {
    useJUnitPlatform(){
        includeTags "suite_clickhouse_api_service"
    }
}

task testConnectionSearchApiService(type: Test) {
    useJUnitPlatform(){
        includeTags "suite_connection_search_service"
    }
}

task testEventGeneratorService(type: Test) {
    useJUnitPlatform(){
        includeTags "suite_event_generator_service"
    }
}

task testRuleEngineService(type: Test) {
    useJUnitPlatform(){
        includeTags "suite_rule_engine_service"
    }
}

sourceSets {
    main {
        java {
            srcDir "${buildDir}/generated/src/main/java"
        }
    }
}