# URLs
baseUrlE2e=http://k8s-test-nginxrev-55e209d446-410128713.us-east-1.elb.amazonaws.com/
baseUrlVantageAccount=https://secure-broccoli.crm-alpha.com
# Settings
headlessMode=false
timeout=30000
pathTraceVideo=test-output/videos/
pathTrace=playwright-report/trace
pathBaselineScreenshot=visual-comparsion/baseline-screenshots/
# Kafka
kafkaHost=localhost
kafkaPort=9092
kafkaCoreIncomingTopic=topic
kafkaCoreOutcomingTopic=topic
backOfficeKafkaPrivate =b-2.riskantifraudtestcore.vf8fc5.c19.kafka.us-east-1.amazonaws.com:9096
backOfficeKafkaPublic =b-3-public.riskantifraudtestcore.vf8fc5.c19.kafka.us-east-1.amazonaws.com:9196
backOfficeKafkaPassword = Mz2Xq6BQb3P2y1StQ10g!
# Database
postgreHost=jdbc:postgresql://localhost/test
postgreLogin=login
postgrePassword=password
mysqlStagingCrmHost=jdbc:mysql://db01.crm-alpha.com:3306/
mysqlStagingCrmLogin=riskteam_r
mysqlStagingCrmPassword=uSZ_r!6yK3>0u(.28kk_rZ(GhlJU)E
# Registration Helper
registrationHelperLogin=testregmarkets
registrationHelperPassword=147258
# Clickhouse api helper
clickhouseBasePath=http://k8s-test-clickhou-b7d79505f3-29598191.us-east-1.elb.amazonaws.com
clickhouseGetClientPath=/v1/clients/
# Clickhouse database
clickhouseHost=jdbc:clickhouse://v491rvx4dz.us-east-1.aws.clickhouse.cloud:8443/consolidated?ssl=true
clickhouseUser=nkoriagin
clickhousePassword=
# Other data
countryMalaysia=Malaysia
# Don't forget to add this file to gitignore when active develop starts