# URLs
baseUrlE2e=https://backoffice.vindex-test.risk-vantagefx.com/
enterPageE2E=https://risk-keycloak-dev.risk-vantagefx.com/realms/vims/protocol/openid-connect/auth?response_type=code&client_id=backoffice-test&redirect_uri=http%3A%2F%2Fk8s-test-nginxrev-55e209d446-410128713.us-east-1.elb.amazonaws.com
baseUrlVantageAccount=https://secure-core-au.crm-alpha.com
crmEmulatorBaseUrl=https://k8s-test-emulator-494a3d6a1c-682544496.us-east-1.elb.amazonaws.com
# Settings
headlessMode=false
timeout=30000
pathTraceVideo=test-output/videos/
pathTrace=playwright-report/trace
pathBaselineScreenshot=visual-comparsion/baseline-screenshots/
# Kafka
testClusterKafkaPrivate=b-2.riskantifraudtestcore.vf8fc5.c19.kafka.us-east-1.amazonaws.com:9096
testClusterKafkaPublic=b-3-public.riskantifraudtestcore.vf8fc5.c19.kafka.us-east-1.amazonaws.com:9196
testClusterKafkaPassword=OTv2W741kaXe8Wn99J!
testClusterKafkaConsumerGroup1=coretest
testClusterKafkaConsumerGroup2=coretest2
# Database
mysqlStagingCrmHost=jdbc:mysql://db01.crm-alpha.com:3306/
mysqlStagingCrmLogin=riskteam_r
mysqlStagingCrmPassword=uSZ_r!6yK3>0u(.28kk_rZ(GhlJU)E
# Registration Helper
registrationHelperLogin=testregmarkets
registrationHelperPassword=147258
# Clickhouse api helper
clickhouseBasePathTest=http://clickhouse-api.vindex-test.risk-vantagefx.com
clickhouseBasePathProd=http://clickhouse-api.vindex.risk-vantagefx.com
clickhouseGetClientPath=/v1/clients/
clickhouseGetClientsPath=/v1/clients
clickhouseGetClientTradingAccountsPath=/v1/clients/{clientId}/tradingAccounts
clickhouseGetTradesGroupByPath=/v1/tradesGroupBy
clickhouseGetTradesPath=/v1/trades
clickhouseGetUnclosedTradesPath=/v1/unclosedTrades
clickhouseGetDepositsPath=/v1/deposits
clickhouseGetWithdrawalsPath=/v1/withdrawals
clickhouseGetCreditsPath=/v1/credits
clickhouseGetBonusesPath=/v1/bonuses
clickhouseGetCreditEquityRatio=/v1/creditEquityRatio
clickhouseGetMirrorAccountsByTrades=/v1/mirrorAccountsByTrades
clickhouseGetLexisNexisPath=/v1/lexisNexis
clickhouseGetLexisNexisDataPath=/v1/lexisNexis/data
clickhouseGetAbuseTypes=/v1/abuseTypes
clickhouseGetFloatingTradesGroupBy=/v1/floatingTradesGroupBy
clickhouseGetCreditRiskFreeRevenueRatio=/v1/creditRiskFreeRevenueRatio
clickhouseGetSwapFreeFees=/v1/swapFreeFees
clickhouseGetSwapFreeVolumes=/v1/swapFreeVolumes
clickhouseGetBalanceOrders=/v1/balanceOrders
clickhouseGetFastTrades=/v1/fastTrades
clickhouseGetLexisNexisV2=/v2/lexisNexis
clickhouseGetTradesByTradeId=/v1/trades/{tradeId}
clickhouseGetTotalLoyalties=/v1/totalLoyalties
clickhouseGetMirrorClientsByTrades=/v1/mirrorClientsByTrades
clickhouseGetFinancialCalendar=/v1/financialCalendar
clickhouseGetDummyTradeData=/v1/dummyTradeData
clickhouseGetAccountBalance=/v1/accountBalance
clickhouseGetAbnormalProfit=/v1/abnormalProfit
# Rule engine
ruleEngineBasePathTest=https://rule-engine.vindex-test.risk-vantagefx.com
ruleEngineGetBrands=/v1/brands
ruleEngineGetEvents=/v1/events
ruleEngineRules=/v1/rules
ruleEngineRuleDeployment=/v1/rule-deployments
ruleEngineRuleDeploymentByUuid=/v1/rule-deployments/{uuid}
# Mirror trading score service
mirrorTradingScoreGetScore=/v1/mirrorScore
# Connection search
connectionSearchBasePathTest=https://connection-search.vindex-test.risk-vantagefx.com
connectionSearchBasePathProd=https://connection-search.vindex.risk-vantagefx.com
connectionSearchGetConnectionsByClient=/v1/connections/byClientId
connectionSearchGetConnectionsByAttributes=/v1/connections/byAttributes
connectionSearchGetAbuseTypesByClient=/v1/abuseTypes/byClientId
connectionSearchGetAbuseTypesByAttributes=/v1/abuseTypes/byAttributes
connectionSearchGetCheckConnectedIb=/v1/connections/checkConnectedIb
# Mitigation service
mitigationServiceBasePath=https://mitigation-e2e.vindex-test.risk-vantagefx.com
mitigationServiceInsightBasePath=https://mitigation.vindex-test.risk-vantagefx.com/external/insight
mitigationServiceGetRestrictionCatalog=/restrictionCatalog
mitigationServiceRestrictions=/restrictions
mitigationServiceCancelRestriction=/restrictions/%s/cancel

# Mitigation service db
mitigationDbSshHost=ec2-18-212-95-208.compute-1.amazonaws.com
mitigationDbSshPort=22
mitigationDbSshUser=ec2-user
mitigationDbSshPrivateKey=src/main/resources/config/test-kp-2.pem
mitigationDbHost=risk-antifraud-test-coreservices-test-rds-prostgres.c5kuyg0oy1r6.us-east-1.rds.amazonaws.com
mitigationDbPort=5432
mitigationDbUser=mitigation_backend_app_user
mitigationDbPassword=sVT6JjB5rSKtLuQKIaFMuA==
mitigationDbName=postgres
# Postgres db
postgresDbSshHost=ec2-18-212-95-208.compute-1.amazonaws.com
postgresDbSshPort=22
postgresDbSshUser=ec2-user
postgresDbSshPrivateKey=src/main/resources/config/test-kp-2.pem
postgresDbHost=risk-antifraud-test-coreservices-test-rds-prostgres.c5kuyg0oy1r6.us-east-1.rds.amazonaws.com
postgresDbPort=5432
postgresDbUser=postgres
postgresDbPassword=:y<QnTY90E_C0_:VVc]5MPf1Jj_e
postgresDbName=postgres
# Audit service db
auditDbName=postgres
auditDbUser=audit_backend_app_user
auditDbPassword=UwNQGsX6agdFxT/ufmLwtw==
# Backoffice service db
backofficeDbName=postgres
backofficeDbUser=backoffice_backend_app_user
backofficeDbPassword=R5p40ejL603wO2tjiE6/RQ==
# Rule engine Db
ruleEngineDbName=postgres
ruleEngineDbUser=rule_engine_app_user
ruleEngineDbPassword=QBOK+y0b5Ss0tAeWfsKGwA==
# Backoffice DB general
postgresDBHost=risk-antifraud-test-coreservices-test-rds-prostgres.c5kuyg0oy1r6.us-east-1.rds.amazonaws.com
# Clickhouse database
clickhouseHost=jdbc:clickhouse://v491rvx4dz.us-east-1.aws.clickhouse.cloud:8443/consolidated?ssl=true
clickhouseUser=nkoriagin
clickhousePassword=x0?XEE=O8?sMEjXy
# Other data
countryMalaysia=Malaysia
#
crmIntegrationUserId=10085436
crmIntegrationUserUcid=vantage-10085436
# Backoffice UI users
idFirstLogin=3264cd0e-46a9-46e6-99c0-c36ca8cb74c6
usernameFirstLogin=backoffice-test2@vindex.com
passwordFirstLogin=123QWErty!
firstNameFirstLogin=backoffice-test2
lastNameFirstLogin=backoffice-test2
emailFirstLogin=backoffice-test2@vindex.com
idCore=e6775a8e-0a7f-42bc-a8ca-48406e5a2b59
usernameCore=coreTest
passwordCore=Test1234!
emailCore=coretest@test.com
firstNameCore=Core
lastNameCore=Test
idDev=51d4effa-9299-4b60-b97d-c063cf8685e4
usernameDev=dev
passwordDev=123
emailDev=dev@testmail.com
firstNameDev=devFirstName
lastNameDev=devLastName
idAutotestOne=6eeee937-7409-48ab-ac89-b00e3a798dc9
usernameAutotestOne=backoffice-test@vindex.com
passwordAutotestOne=123QWErty!
emailAutotestOne=backoffice-test@vindex.com
firstNameAutotestOne=backoffice-test
lastNameAutotestOne=backoffice-test
usernameAutotestAF=backoffice-test-mezovo@vindex.com
passwordAutotestAF=123Qwerty!