# URLs
baseUrlE2e=https://www.wikipedia.org
baseUrlVantageAccount=https://secure-broccoli.crm-alpha.com
# Settings
headlessMode=false
timeout=30000
# Kafka
kafkaHost=localhost
kafkaPort=9092
kafkaCoreIncomingTopic=topic
kafkaCoreOutcomingTopic=topic
backOfficeKafkaPrivate =b-2.riskantifraudtestcore.vf8fc5.c19.kafka.us-east-1.amazonaws.com:9096
backOfficeKafkaPublic =b-3-public.riskantifraudtestcore.vf8fc5.c19.kafka.us-east-1.amazonaws.com:9196
backOfficeKafkaPassword = 12345678
# Database
postgreHost=jdbc:postgresql://localhost/test
postgreLogin=login
postgrePassword=password
mysqlStagingCrmHost=jdbc:mysql://db01.crm-alpha.com:3306/
mysqlStagingCrmLogin=riskteam_r
mysqlStagingCrmPassword=uSZ_r!6yK3>0u(.28kk_rZ(GhlJU)E
# Registration Helper
registrationHelperLogin=testregmarkets
registrationHelperPassword=147258
registrationHelperFirstName=testregmarkets
registrationHelperSecondName=testregmarkets
registrationHelperRegulator=VFSC2
registrationHelperWid=AU
registrationHelperRegistrationInterface=/api/registrationV2/register
# Other data
countryMalaysia=Malaysia
# Don't forget to add this file to gitignore when active develop starts