openapi: 3.0.0
info:
  title: Client Data API
  version: '1.0'
paths:
  /v1/clients/{clientId}:
    get:
      summary: Get Client Data
      operationId: getClientData
      description: Retrieves client data identified by brand, regulator, and user ID.
      parameters:
        - in: path
          name: clientId
          schema:
            type: string
          required: true
          description: Unique user identifier.

      responses:
        '200':
          description: Successful response with client data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        '400':
          description: Bad request due to invalid or missing parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Client not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Client:
      type: object
      properties:
        websiteUserType:
          type: string
        clientId:
          type: string
        regulator:
          type: string
        phoneNum:
          type: string
        phoneCountryCode:
          type: string
        updateTime:
          type: string
          format: date-time
        lastName:
          type: string
        twoFaUser:
          type: boolean
        firstName:
          type: string
        email:
          type: string
          format: email
        createTime:
          type: string
          format: date-time
        countryCode:
          type: string
        brand:
          type: string
        birthday:
          type: string
          format: date
        registrationDate:
          type: string
          format: date
      required:
        - websiteUserType
        - clientId
        - regulator
        - phoneNum
        - phoneCountryCode
        - updateTime
        - lastName
        - twoFaUser
        - firstName
        - email
        - createTime
        - countryCode
        - brand
        - registrationDate

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Description of the error.
        status:
          type: integer
          description: HTTP status code of the error.